### ISSUE TITLE
File Extensions

### ISSUE THREAD

**Issue by JonathanRowell** [wcandillon/grunt-xqlint#3]
The allowable file extensions are fixed in the source to 'xq' and 'jq'. Unfortunately the eXist database system requires for package installation a fixed name of pre-install.xql. Could you possibly add to the options an optional array of file extension which will be used in the search? Default would be the two you have now.

**Comment by wcandillon** [comment]
Which other extensions would you like to see added? just xql?

**Comment by JonathanRowell** [comment]
I have just checked with the newest source of eXist and the extension .xq is actually allowed. I have changed all of my files to use this extension, which seems to be the standard. I would suggest that you either close this issue or build an option in to allow the user to select his file extensions.
