### ISSUE TITLE
EISDIR Error

### ISSUE THREAD

**Issue by JonathanRowell** [wcandillon/grunt-xqlint#6]
Threw away all node_modules, updated PACKAGE.JSON for grunt-xqlint to 1.0.0, npm init, and ran Gruntfile. Got message "Warning: EISDIR, illegal operation on a directory Used --force, continuing." No files were linted (because I deliberately included an error).

**Comment by wcandillon** [comment]
Yes because the input has changed? Check out the readme. Keep me posted.

**Comment by JonathanRowell** [comment]
Brilliant! I have used the array and selector to target the xq files and it now runs much, much faster.

Sorry for not reading the README.
